### ISSUE TITLE
Profile page breaks due to empty description

### ISSUE THREAD

**Issue by birkskyum** [acterglobal/code#870]
I got the page running local, but when trying to access my profile page, I'm met with this:

<img width="992" alt="Screen Shot 2022-10-19 at 12 34 38" src="https://user-images.githubusercontent.com/74932975/196670896-dfe4d8a7-3246-4b83-953c-6484d9aeb5c0.png">

I believe it's because I don't have any profile text.

**Comment by emilvincentz** [comment]
@orbiteleven maybe you know what it could be?
